# -*- coding: utf-8 -*-
"""SentimentAnalysis(RF).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0YsKmbKLtPdLKFg_rMPfsVMjQOhaadU
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle
import matplotlib.pyplot as plt

df = pd.read_csv('IMDB Dataset.csv')
print(df.shape)

df['review'] = df['review'].str.lower().str.replace('[^\w\s]', '')  # Lowercase and remove punctuation
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})  # Encode sentiment labels

vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))  # Includes unigrams and bigrams
X = vectorizer.fit_transform(df['review']).toarray()
y = df['sentiment']
print("TF-IDF feature extraction complete. Shape:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)  # Binary predictions
y_prob = rf_model.predict_proba(X_test)[:, 1]  # Probabilities for positive class

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print(f"RF Accuracy: {accuracy:.2f}")
print("Confusion Matrix:\n", conf_matrix)
print(f"AUC Score: {roc_auc:.3f}")

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {roc_auc:.3f})')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

pickle.dump(rf_model, open('rf_sentiment_model_tfidf.pkl', 'wb'))
pickle.dump(vectorizer, open('vectorizer_tfidf.pkl', 'wb'))
print("Model and vectorizer saved.")

from google.colab import files

files.download('rf_sentiment_model_tfidf.pkl')